pages:
  stage: deploy
  image: python:latest
  script:
    - /home/gitlab-runner/.local/bin/mkdocs build --site-dir public
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'